name: Testing

on:
  push:
    branches: [ deno ]
  pull_request:
    branches: [ deno ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2.2.0
      - run: |
          deno --version
          deno test --unstable --allow-read 
